{
    parserClass="com.lomovtsev.xitsupport.XitParser"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"
    psiClassPrefix="Xit"
    psiPackage="com.lomovtsev.xitsupport.psi"
    psiImplPackage="com.lomovtsev.xitsupport.psi.impl"

    elementTypeHolderClass="com.lomovtsev.xitsupport.psi.XitTypes"
    elementTypeClass="com.lomovtsev.xitsupport.XitElementType"
    tokenTypeClass="com.lomovtsev.xitsupport.XitTokenType"

}

xitFile ::= item_*
private item_ ::= (xitGroup | NEWLINE)
//property ::= (KEY? SEPARATOR VALUE?) | KEY

//xitGroup ::= (header point)
//header ::= (newline sentence newline)
//point ::= ((NEW_TASK | DONE_TASK | ONGOING_TASK | OBSOLETE_TASK) sentence newline)
//sentence ::= (TEXT | whitespace)*

//point ::= (checkbox TEXT NEWLINE)
//checkbox ::= (NEW_TASK | DONE_TASK | ONGOING_TASK | OBSOLETE_TASK)

//points ::= checkbox+


xitGroup ::= (title points GROUP_END) | (points GROUP_END)
title ::= (TITLE_WORD | SPACE)+ NEWLINE
points ::= point+
point ::= (checkbox_part PRIORITY? point_description NEWLINE)
point_description ::= (checkbox_word | SPACE | addition_description)+
addition_description ::= (NEWLINE DESC_INDENT)

checkbox_part ::= (OPEN_CHECKBOX | DONE_CHECKBOX | OBSOLETE_CHECKBOX | ONGOING_CHECKBOX | QUESTION_CHECKBOX)
checkbox_word ::= (OCH_WORD | CCH_WORD | GCH_WORD | OBS_WORD | QUESTION_WORD | HASHTAG)

//groupSeparator ::= NEWLINE NEWLINE


//OPEN_CHECKBOX
//DONE_CHECKBOX
//ONGOING_CHECKBOX
//OBSOLETE_CHECKBOX
//WORD
//SPACE
//DESC_INDENT
//GROUP_END
//
//OCH_WORD
//TITLE_WORD